### ISSUE TITLE
Multiple output formats support

### ISSUE THREAD

**Issue by macro187** [macro187/testrunner#3]
Refactor TestRunner to support different output formats, with an initial "default" format producing the current format.

**Comment by vnekatesharao** [comment]
I am using this tool to execute net framework unit tests,  and it works great.  The thing that is missing is that the test execution report.  currently the results are displaying on the console and it is not helping to see those results in reporting dash boards.  It would be really good if the tool can produce test execution summary in the form of trx format..  So that it can then be published to reporting server

**Comment by macro187** [comment]
Created separate issue #16 for .trx file format support

**Comment by macro187** [comment]
Done, with initial `human` and `machine` output formats.
